###check server status
GET http://localhost:8000

#============Admin API
### post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"praveen",
    "lName":"sf",
    "email":"sdsfcdcdgdffdsdfsfgddsfsd@sfdgdsfsdfdfefs.com",
    "password":"sgg",
    "phone":"sdfsf",
    "address":"sdfgsdf",
    "dob":"01/02/2023"
}

###testing login
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
   
    "email":"sdsfcdcdgdffdsdfsfgddsfsd@sfdgdsfsdfdfefs.com",
    "password":"sgg"
    
}

###testing category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"active",
    "name":"Electronics",
    "parentId":""

}

###get category
get http://localhost:8000/api/v1/category

###get category
get http://localhost:8000/api/v1/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkc2ZjZGNkZ2RmZmRzZGZzZmdkZHNmc2RAc2ZkZ2RzZnNkZmRmZWZzLmNvbSIsImlhdCI6MTcwNDkzMzM0MSwiZXhwIjoxNzA0OTM0MjQxfQ.Lirc0OnE-WWyZD-LcUFuPwNhUJiafZmuO69YQtBf5iQ
